modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="expirementmod"
version="${file.jarVersion}"
displayName="Experiment Mod"
authors="Sajevius and Aqu (both code and assets)"
description='''Just some random test mod. Don't mind us.'''

[[dependencies.expirementmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.expirementmod]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"
